### ISSUE TITLE
Make a release with binaries

### ISSUE THREAD

**Issue by Dimava** [dteviot/MergeWebToEpub#3]
Please make a github release with .exe file, so it may be easily downloaded and used

**Comment by Dimava** [comment]
Mkay, I have somehow found a working link to your [googledrive](https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8), but binaries should be accessible from github anyway
Github allows uploading files into releases for a reason

**Comment by Dimava** [comment]
Howto: 
- go to https://github.com/dteviot/MergeWebToEpub/releases/new
- drop a zip with exe and dlls to the 
![image](https://user-images.githubusercontent.com/20068737/135522909-2802410b-374b-43f7-b6b8-9df9e1c1ab7f.png)
field
- publish release

**Comment by dteviot** [comment]
Read me updated with location of pre-built files.
