### ISSUE TITLE
Add txt format output

### ISSUE THREAD

**Issue by nolepguy** [dteviot/MergeWebToEpub#8]
Please add txt file format as option to export. Of course I can download the epub version and convert it using online converter, but the problem is that the txt file is only one for all chapters (you can easily lose track). It's better for the txt file to be separated per chapters and packed in zip.

**Comment by dteviot** [comment]
@nolepguy 

Test version for Windows has been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the instructions at https://github.com/dteviot/MergeWebToEpub to install and use.
Note, there's a new "Save as text files" option on the save menu.  So steps are
1. Install MergeWebToEpub
2. Start MergeWebToEpub
3. On File menu, select "open"
4. Once epub has been loaded, select "Save as text files".  This will save as single zip.

Please let me know how it goes.

Note, XHTML to text conversion might need to be tweaked to add more whitespace.

For my notes: 135 minutes work

**Comment by nolepguy** [comment]
Thanks, it works perfectly
